## Stage 1 : build with maven builder image with native capabilities
FROM registry.redhat.io/quarkus/mandrel-for-jdk-21-rhel8:23.1 AS build

COPY --chown=quarkus:quarkus mvnw /code/mvnw
COPY --chown=quarkus:quarkus .mvn /code/.mvn
COPY --chown=quarkus:quarkus pom.xml /code/


USER quarkus
WORKDIR /code
RUN ./mvnw -B -Pnative org.apache.maven.plugins:maven-dependency-plugin:3.6.1:go-offline
COPY --chown=quarkus:quarkus src /code/src
RUN ./mvnw verify -B -Pnative -Dmaven.test.skip=true -Dquarkus.native.native-image-xmx=8g

## Stage 2 : create the docker final image
FROM registry.redhat.io/ubi9/ubi-minimal:9.4

LABEL description="Red Hat Agent Morpheus - UI"
LABEL io.k8s.description="Red Hat Agent Morpheus - UI"
LABEL io.k8s.display-name="Agent Morpheus UI"
LABEL io.openshift.tags="agent morpheus ui"
LABEL summary="The Agent Morpheus UI allows interacting with the Agent Morpheus service"

WORKDIR /work/
COPY --from=build /code/target/*-runner /work/application

# set up permissions for user `1001`
RUN chmod 775 /work /work/application \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]