package com.redhat.ecosystemappeng.morpheus.model.audit;

public enum MetricName {
    INTEL_SCORE_FIDELITY,
    JUSTIFICATION_QUALITY,
    SUMMARY_QUALITY,
    AGENT_LOOP_TOOL_SELECTION_QUALITY,
    AGENT_LOOP_TOOL_CALL_INTEGRITY,
    AGENT_LOOP_REASONING_QUALITY,
    AGENT_LOOP_ANSWER_QUALITY,
    CHECKLIST_PROMPT_ALIGNMENT,
    CHECKLIST_QUALITY
}
