package com.redhat.ecosystemappeng.morpheus.model.audit;

public enum MetricName {
    CHECKLIST_PROMPT_ALIGNMENT,
    CHECKLIST_CVE_RELEVANCY,
    CHECKLIST_VULNERABILITY_COMPLETENESS,
    CHECKLIST_ACTIONABILITY,
    CHECKLIST_PRIORITIZATION,
    AGENT_ANSWER_QUALITY,
    AGENT_REASONING_QUALITY,
    AGENT_TOOL_SELECTION_QUALITY,
    SUMMARY_STRUCTURE,
    SUMMARY_VERDICT_ACCURACY,
    SUMMARY_EVIDENCE_CITATION,
    SUMMARY_FAITHFULNESS,
    JUSTIFICATION_LABEL_SUMMARY_CONSISTENCY,
    JUSTIFICATION_REASON_SUMMARY_CONSISTENCY,
    JUSTIFICATION_LABEL_REASON_CONSISTENCY
}
